In [14]:
import sklearn
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

X = np.array([1,2,3,4,5,8,9]).reshape(-1,1)
X 

Y = np.array([4,5,7,8,9,10,12])

model = LinearRegression().fit(X,Y)

cv = cross_val_score(model, X, Y, cv=3, scoring='neg_mean_absolute_error')
print(cv)

prediction = model.predict(np.array([6]).reshape(-1,1))
print(prediction)


[-1.37254902 -0.9906015  -2.75      ]
[9.14893617]


LogisticRegression

In [18]:
# Create an array with a range of values
range_arr = np.arange(0, 15, 2)
range_arr
for i in range_arr:
    print(model.predict(np.array([i]).reshape(-1,1)))

[3.72340426]
[5.53191489]
[7.34042553]
[9.14893617]
[10.95744681]
[12.76595745]
[14.57446809]
[16.38297872]


In [23]:
# Create an array with random values
random_arr = np.random.random((2, 3))
random_arr

array([[0.23306535, 0.75312262, 0.75273473],
       [0.59788594, 0.01084783, 0.93963781]])

In [24]:
mean = np.mean(random_arr)
mean

0.5478823788835044

In [28]:
median = np.min(random_arr)
median

0.01084782513672522

In [34]:
# Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5,6])
arr = np.reshape(arr1, (2,3))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arrr = arr.flatten()
arrr

array([1, 2, 3, 4, 5, 6])

Pandas

In [37]:
import pandas as pd
data = {'name': ['John', 'Paul', 'George', 'Ringo'],
        'age': [22, 23, 24, 25]}

df = pd.DataFrame(data)
df

name  age
0    John   22
1    Paul   23
2  George   24
3   Ringo   25

In [44]:
df

name  age
0    John   22
1    Paul   23
2  George   24
3   Ringo   25

In [50]:
row = df.loc[1]

row

name    Paul
age       23
Name: 1, dtype: object

LOOPS, Data Structure

In [78]:
fruits = ['apple', 'banana', 'cherry']
for fruit in fruits:
    print(fruit)

fruits.append('orange')
fruits
fruits.remove('banana')
fruits

apple
banana
cherry


['apple', 'cherry', 'orange']

In [68]:
# Create a tuple / is immutable
my_tuple = (1, 2, 3,6)
len(my_tuple)

4

In [69]:
# Create a set / is unordered and unindexed
my_set = {1, 2, 3, 4, 5, 6}
my_set.add(7)
my_set.remove(5)
my_set

{1, 2, 3, 4, 6, 7}

In [81]:
# Create a dictionary / is a collection of key-value pairs
my_dic = {'name': 'John', 'age': 22}
my_dic['city'] = 'chicago'
del my_dic['age']
my_dic

list_key = []
list_values = []

for key, values in my_dic.items():
    print(key, values)
    list_key.append(key)
    list_values.append(values)
print(list_key)
print(list_values)

name John
city chicago
['name', 'city']
['John', 'chicago']


In [86]:
# Create a function that find the maximum value in a list
def find_max_value(list):
    max_value =  max(list)
    return max_value
print(find_max_value([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))
print(max([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))

10
10


In [104]:
def count_vowels(s):
    vowels = 'aeiou'
    count = 0
    for char in s:
        if char.lower() in vowels:
            count += 1
    return count

# Test
print(count_vowels("Hello World"))  # Output: 3


3


In [4]:
pip install docx

     ---------------------------------------- 0.0/54.9 kB ? eta -:--:--
     -------------- ----------------------- 20.5/54.9 kB 320.0 kB/s eta 0:00:01
     --------------------- ---------------- 30.7/54.9 kB 325.1 kB/s eta 0:00:01
     -------------------------------------- 54.9/54.9 kB 406.2 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.8 MB 660.6 kB/s eta 0:00:06
    --------------------------------------- 0.1/3.8 MB 825.8 kB/s eta 0:00:05
    --------------------------------------- 0.1/3.8 MB 751.6 kB/s eta 0:00:05
   - -------------------------------------- 0.1/3.8 MB 774.0 kB/s eta 0:00:05
   -- ------------------------------------- 0.2/3.8 MB 841.6 kB/s eta 0:00:05
   -- ------------------------------------- 0.2/3.8 MB 811.5 kB/s eta 0:00:05
   -- ------------------------------------- 0.3/3


[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
pip install exceptions

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement exceptions (from versions: none)
ERROR: No matching distribution found for exceptions

[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import docx
from docx import Document

# Load the document
doc_path = "grillevide.docx"
doc = Document(doc_path)

# Define the details to fill
research_question = "Dans quelle mesure l'utilisation de modèles de langage massifs comme ChatGPT influence-t-elle positivement ou négativement l'éducation et l'enseignement ?"
bibliography = """Cadre théorique mobilisé :
- Vygotsky, L. (1978). Mind in Society: The Development of Higher Psychological Processes.
- Bandura, A. (2007). Auto-efficacité : le sentiment d’efficacité personnelle.
- Venkatesh, V., & Bala, H. (2008). Technology acceptance model 3 and a research agenda on interventions. Decision Sciences, 39(2), 273–315.

Lien avec l'outil de recueil :
Utiliser la théorie socio-constructiviste de Vygotsky pour comprendre comment les outils d'IA comme ChatGPT facilitent l'apprentissage collaboratif.
Appliquer le modèle de l'auto-efficacité de Bandura pour analyser la motivation des élèves.
Mobiliser le modèle d'acceptation de la technologie (TAM) de Venkatesh et Bala pour évaluer l'acceptation de ChatGPT par les enseignants."""

questions = """Questions :
1. Comment les enseignants perçoivent-ils l'intégration de ChatGPT dans leurs pratiques pédagogiques ?
    - Hypothèse : La perception positive des enseignants envers ChatGPT facilite son adoption et son utilisation efficace en classe.
2. Quels sont les impacts de l'utilisation de ChatGPT sur la motivation des élèves ?
    - Hypothèse : L'utilisation de ChatGPT augmente la motivation des élèves en rendant l'apprentissage plus interactif et personnalisé.
3. Dans quelle mesure ChatGPT facilite-t-il ou entrave-t-il la collaboration entre les élèves ?
    - Hypothèse : ChatGPT facilite la collaboration entre les élèves en fournissant des outils de communication et de partage de connaissances en temps réel.
4. Quels sont les avantages et les inconvénients de l'utilisation de ChatGPT dans l'éducation selon les différents acteurs (enseignants, élèves, administrateurs) ?
    - Hypothèse : Les avantages perçus incluent une meilleure personnalisation de l'enseignement et une augmentation de l'engagement des élèves, tandis que les inconvénients peuvent inclure des préoccupations liées à la dépendance à la technologie et à la confidentialité des données."""
discussion_themes = """Thèmes de discussion :
1. Les expériences des enseignants avec ChatGPT dans leur enseignement.
2. Les changements observés dans la motivation et l'engagement des élèves.
3. Les exemples spécifiques de collaboration entre élèves facilitée ou entravée par ChatGPT.
4. Les avantages et les défis rencontrés dans l'intégration de ChatGPT."""
question_sequence = """Enchaînement des questions :
1. Pouvez-vous décrire vos premières impressions lorsque vous avez commencé à utiliser ChatGPT dans votre classe ?
2. Comment ChatGPT a-t-il influencé la motivation et l'engagement de vos élèves ?
3. Pouvez-vous donner des exemples de situations où ChatGPT a facilité la collaboration entre vos élèves ?
4. Quels sont, selon vous, les principaux avantages et inconvénients de l'utilisation de ChatGPT dans votre enseignement ?
5. Comment évaluez-vous la formation et le soutien que vous avez reçus pour utiliser ChatGPT ?"""

# Fill in the sections of the document based on the identified table structure
def fill_table(table, row, column, text):
    table.cell(row, column).text = text

# Identify the table and fill in the sections
table = doc.tables[0]
fill_table(table, 0, 1, research_question)
fill_table(table, 1, 1, bibliography)
fill_table(table, 2, 1, questions)
fill_table(table, 3, 1, discussion_themes)
fill_table(table, 4, 1, question_sequence)

# Save the filled document
filled_doc_path = "filled_grille_v3.docx"
doc.save(filled_doc_path)

filled_doc_path


ModuleNotFoundError: No module named 'exceptions'

In [1]:
import requests
import time
import webbrowser

url = "https://aadl3inscription2024.dz"
print("...")
while True:
  try:
    response = requests.get(url, timeout=30) 
    if response.status_code == 200:
      print("Accès au site réussi!")
      webbrowser.open(url)
      break
    else:
      print(f"Erreur: {response.status_code}. Nouvelle tentative dans 5 secondes...")
  except requests.exceptions.RequestException as e:
      print(f"Exception: {e}. Nouvelle tentative dans 5 secondes...||")
      time.sleep(5)

...
Exception: HTTPSConnectionPool(host='aadl3inscription2024.dz', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000023DAFECEB40>, 'Connection to aadl3inscription2024.dz timed out. (connect timeout=30)')). Nouvelle tentative dans 5 secondes...||
Exception: HTTPSConnectionPool(host='aadl3inscription2024.dz', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000023DB028A510>, 'Connection to aadl3inscription2024.dz timed out. (connect timeout=30)')). Nouvelle tentative dans 5 secondes...||
Exception: HTTPSConnectionPool(host='aadl3inscription2024.dz', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000023DB0289F40>, 'Connection to aadl3inscription2024.dz timed out. (connect timeout=30)')). Nouvelle tentative dans 5 secondes...||
Exception: HTTPSConnectionPool(host=